/**
 * WikiAccount Class
 * Handles user-specific actions including metadata, verification, emailing, and rights management.
 */
export class WikiAccount {
  constructor( session ) { this.session = session; }

  /**
   * Sends an email to a wiki user.
   * 
   * @param { Object } params - Parameters for action=emailuser (target, subject, text).
   * @returns { Promise<Object|null> }
   */
  async email( params ) {
    try {
      if ( !params.token ) params.token = await this.session.tokens.get( 'csrf' );
      const res = await this.session._post( { action: 'emailuser', ...params } );
      return res.emailuser;
    }
    catch ( e ) {
      console.error( '[Wiki] Email failure: ' + e.message );
      return null;
    }
  }

  /**
   * Retrieves account information for specific users.
   * 
   * @param { Object } params - Parameters for list=users.
   * @returns { Promise<Array|null> }
   */
  async get( params ) {
    try {
      const res = await this.session._post( {
        action: 'query',
        list: 'users',
        usprop: 'blockinfo|registration|editcount|groups',
        ...params
      } );
      return res.query.users;
    }
    catch ( e ) {
      console.error( '[Wiki] Account fetch failure: ' + e.message );
      return null;
    }
  }

  /**
   * Changes a user\'s group memberships.
   * 
   * @param { Object } params - Parameters for action=userrights (user, add, remove).
   * @returns { Promise<Object|null> }
   */
  async rights( params ) {
    try {
      if ( !params.token ) params.token = await this.session.tokens.get( 'userrights' );
      const res = await this.session._post( { action: 'userrights', ...params } );
      return res.userrights;
    }
    catch ( e ) {
      console.error( '[Wiki] Rights change failure: ' + e.message );
      return null;
    }
  }

  /**
   * Validates if a specific token exists on a user\'s Discord.json subpage.
   * 
   * @param { string } username - The wiki username to check.
   * @param { string } token - The unique code generated by the Discord bot.
   * @returns { Promise<Object|null> }
   */
  async verify( username, token ) {
    try {
      const res = await this.session._post( {
        action: 'query',
        prop: 'revisions',
        titles: 'User:' + username + '/Discord.json',
        rvprop: 'content|ids',
        rvslots: 'main'
      } );
      const page = res.query.pages;
      if ( !page || page.missing ) return null;
      const revision = page.revisions;
      if ( !revision.slots.main.content.includes( token ) ) return null;
      return { pageid: page.pageid, revid: revision.revid };
    }
    catch ( e ) {
      console.error( '[Wiki] Verification failure: ' + e.message );
      return null;
    }
  }
}
